function [H_speedM,H_heelM] = converge(...
    Vw,...
    rho,...
    mu,...
    S_span,...
    S_avg_ch,...
    S_area,...
    S_alpha,...
    S_mass,...
    S_mast_pos,...
    H_par,...
    H_speed,...
    H_heel,...
    H_heading,...
    K_length,...
    K_weight,...
    M)

i=1; % used for recording
S_area_M=S_area;
difference=1;

while (difference > 0.0001) 
    % Compute
    [S_thrust,S_torque,apparent_wind_angle]=sail(Vw, rho, mu, M, S_area_M, S_avg_ch, S_alpha, S_span, S_mass, H_speed, H_heel, H_heading);
    [H_heel]=keel(S_torque, K_length, K_weight);
    [H_speed]=hull(S_thrust, H_par);
    
    % Rectify Area
    old_S_area_M=S_area_M;
    S_area_M=S_area*cos(H_heel);

    % Record
    H_heelM(i)=rad2deg(H_heel);
    H_speedM(i)=H_speed*1.94384;
    
    % difference
    difference=abs(old_S_area_M-S_area_M);

    i=i+1;
end

end